### ISSUE TITLE
Circular reference makes it rather hard to stop

### ISSUE THREAD

**Issue by EternityForest** [riga/jsonrpyc#9]
It appears that the watchdog threads hang around in the background.  I think what happens is the thread references the watchdog self. self references the RPC, and that keeps the RPC __del__ from getting called.  

For some reason it seems to be possible to close the child process and it's stdio, without the thread ever seeing that it's stdin is closed.

However, if I keep a reference to the original stdin, and add

```python
# test for None keeps linter happy
if self.rpc.original_stdin and self.rpc.original_stdin.closed:
    break
```

into the watchdog loop, it will correctly notice the closure.  I can make a PR with the fix if you'd like?

**Comment by riga** [comment]
Good point about the circular reference. I already merged your PR, so we can close this issue. But I will have another look and see if we can use a weakref to make it even more robust.
